---
title: "Head in The Cloud: How ICT have changed the game for mobility and migration"
author: "Ayra Rowena Reyla and Ana Cecilia Montes"
date: "13 November 2015"
output: pdf_document


highlight: zenburn
theme: united
toc: yes
toc_depth: 3
---


\newpage
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Introduction

Migration is one of the three main determinants of a country's population development. The other two - the birth and death rate - are generally believed to be easier to forecast [@Castles2014]. However, the literature has associated migration to factors that have classically been seen as drivers for migration between two countries such as [a] conditions in the sending country driving out inhabitants, including political troubles, persecution, conflict and other "push factors"", [b] conditions in the receiving country attracting migrants, such as higher wages, better know as "pull factors", and [c] factors which facilitate or authorize the migration process itself, such as the receiving country's immigration politics. 

One driving factor increasingly put forward in recent years is the use of technology. According to @Hiller2004, computer mediated communication has created new possibilities for migrants to maintain strong linkages and ties with their home nations. Not only has new technology improved and heightened communication, it has also bridged cultural gap between countries as it allows people to easily gathering new information and knowledge about other cultures. This of course has made a large impact on people's perception on other cultures and their worldviews. Overall, technology has changed the landscape for communicating, and gathering knowledge and information. These revolutions that have transformed society are making travel and telecommunications cheaper and easier than ever. Moreover, Technology has enhanced the aspects of interaction as it is transforming the way individuals communicate. 

## The Research Question
This primary analysis will attempt to answer the following question using emperical methods: 

Has the increase use of technologies such as internet and mobile phones affected the flow of emigration?


#Methodology

In order to examine the flows of migration, we intend to use data on trends in _International Migrant Stock_ produced by the United Nations. The data contains information from 232 countries and provides the number of migrants by destination and country of origin for four periods of time; 1990, 2000, 2010, and 2013. Moreover, to account for technology diffusion we will use _World Bank indicators_ on the number of Internet users and the number of cellular mobile subscriptions for each country. 

The _International Migrant Stock Total_ indicates the number of people born in a country other than the country in which they currently reside in, this includes refugees as well. The dataset estimates the international migrant stock at a particular time and are mainly collecte from population censuses. 
Also, the dataset presents the estimates of : (1) international migrant stock at mid-year; (2) total population at mid-year (thousands); (3) international migrant stock as a percentage of the total population; (4) annual rate of change of migrant stock (percentage); and (5) estimated number of refugees. The estimates are based on official statistics on the foreign-born or the foreign population. 

This analysis will focus on the estimates for the years 1990, 2000, 2010 and 2013. 

Additionally, in order to conduct a more thourough analysis we will include a number of aggregate metadata collected from _The World Bank indicators_. There are many other determinants of migration, that is why this analysis chooses to include a wide variety of World Bank indicators. The choosen indicators are used to measure certain push factors. 

To measure economic and demographic determinants this analysis includes the _fertility rate_ indicator. Indicators such as _poverty_ and _unemployment_ have been removed from the analysis, as there are many missing values in the dataset. 

To account for political factors the this analysis used  _World Bank Governance indicators_, which includes _government effectiveness_, _regulatory quality_, _rule of law_, and _voice and accountability_. We have ommited _intentional homocides_, _political stability_, and _control of corruption_ indicators because there was a lack of obervations in the data set to conduct a complete analysis. 

#Data Gathering 

This section of the analysis will go into deep detail on our data gathering methods. 

##International Migration Stock, Total

The original data was obtained through the United Nations Population Division, and downloaded through our repository as a Microsoft Excel file. The Excel datasheet had a matrix that described the population outflows and inflows for each country and for several time periods. This analysis focuses four time series; 1990. 2000, 2010 and 2013. 

Gather the data using the *import* command, afterwards we used a loop to import the file to RStudio. Since this analysis is only interested in migration, we only extracted the Migration column from all the countries in the dataset, and created a vector. From each matrix, we only selected the years of interest for this anlaysis. Afterwards we transposed the data to transform it intoo a more usable and readable format, and then we declared it as a dataframe. Using the commant *callnames*, we remaned each column appropriatly. We ended the loop by assigned each year to a specific datafram. Using the command *cbind* we commined all the extrated data from above, thus creating combined year in a singular dataframe. In order to reshape the new dataframe, we used the command *gather*. This takes multiple columns and collapses them into key valye apirs, this created two new variables called _emmigration_ and _year_. Finally, we included the correspondind year names to the specific year variables. 

## World Bank Indicators

To import the indicators we used *install.packages ('WDI)*, afterwards we imported it into our library using *library("WDI")*. Afterwards, we specified which indicators we wanted to include in our analysis by using the specific codes available on the metadata set of the World Bank. We then properly renamed the variables using the *rename* command. Once the data was loaded, we used *Merged <- merge(emigrationtotal, WDI_indi, by = c('iso2c','year'))* to combine the WDI indicators with the International Migration Stock. 

#Inferential Statistics






#Figures




